### ISSUE TITLE
Error message when I run docker stack deploy

### ISSUE THREAD

**Issue by wyattbiker** [jasonmccreary/local-docker-stack#3]
I get the error message when I run the docker deploy command. What should I do here with the vhosts file?

```
$ docker stack deploy -c docker-compose.yml dev
Creating network dev_net
Creating secret dev_db_pwd
open /Users/user1/local-docker-stack/apache/vhosts.conf: no such file or directory
```

The only file in the folder is 
`consolidate-vhosts.sh`
And i dont understand what it is doing

Thanks

**Comment by jasonmccreary** [comment]
You have to create your own `vhosts.conf` file with the Apache config for your local sites. Since I have many local sites, I created this script that reads all of them and consolidates them into a single `vhosts.conf`. You don't have to use it. It is there as a template like the rest of the files in this project.
